### ISSUE TITLE
Tag project

### ISSUE THREAD

**Issue by SpareSimian** [Myrroddin/betterbags-hearthstones#3]
I suggest tagging the project to make it easy to find by BB users. I'm using the tag wow-betterbags-plugin. Click the gear icon to the right of the main project page to bring up project settings and add tags. (I'm open to using a different tag.)

https://github.com/topics/wow-betterbags-plugin

**Comment by Myrroddin** [comment]
Good idea. Which tags do you suggest?

**Comment by SpareSimian** [comment]
I'm using world-of-warcraft, wow-addon, and wow-betterbags-plugin. See my addon here for an example: https://github.com/SpareSimian/BetterBagsShadowlands

**Comment by Myrroddin** [comment]
Sorry for the delay. The project is tagged.
